### ISSUE TITLE
Improve help documentation for cb_add_col_attributes

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/codebookr#6]
# Overview

At the very least, we need to document the five special attributes that cb_add_col_attributes() recognizes. Take directly from README.

The function documentation for `cb_add_col_attributes()` says nothing about the `col_type` attribute. True, it isn't a parameter, but it is a very important attribute. That needs to be may very clear. Probably in the `...` section. We should probably also copy and paste some of the language from cb_add_summary_stats.

If you look at the `cb_get_col_attributes()` code, it looks like `description`, `source`, and `col_type` are attributes that aren't documented in  `cb_add_col_attributes()`, but have special preference.

# codebook()

Just needs to be way more descriptive. We should probably also copy and paste some of the language from cb_add_summary_stats.

# Task list

- [x] Document five special attributes
- [x] Document the col_type attribute in cb_add_col_attributes
- [x] Update the codebook help documentation - see README
- [x] Document the package (https://roxygen2.r-lib.org/articles/rd.html#packages)
